name: CI for Sentinel policies (manual)

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  policy-as-code:
    runs-on: ubuntu-latest
    env:
      SENTINEL_VERSION: 0.26.2
    steps:
      - name: Check-out source code
        uses: actions/checkout@v4
      - name: Install Sentinel CLI
        run: |
          FILENAME="sentinel_${{ env.SENTINEL_VERSION }}_linux_amd64.zip"
          wget "https://releases.hashicorp.com/sentinel/${{ env.SENTINEL_VERSION }}/$FILENAME"
          unzip "$FILENAME" -d $HOME/bin
          chmod +x $HOME/bin/sentinel
          echo "$HOME/bin" >> $GITHUB_PATH
      - name: Run Sentinel tests
        run: sentinel test